#$ -S /bin/bash
#$ -cwd
#$ -q smp.q@@EPP
#$ -j y
#$ -o output_log.txt
##############################################

# Run with: qsub jobSingle.job

echo "Running AMELLIE job script"
module load sge
module load gcc/5.4.0
source /mnt/lustre/projects/epp/general/neutrino/jp643/rat_dependent/rat_source.sh
#source /research/epp/neutrino/snoplus/RAT7/env_rat-7.0.5.sh
cd /mnt/lustre/projects/epp/general/neutrino/jp643/rat_dependent/AMELLIE/

# Run commands
your commands

echo "Finished AMELLIE job."
